// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_63AgXRjW-VW7rp7ACEy_GphjthMIHdY',
    appId: '1:647964169962:web:84773487fbbda6bfe1e993',
    messagingSenderId: '647964169962',
    projectId: 'manage-your-book',
    authDomain: 'manage-your-book.firebaseapp.com',
    storageBucket: 'manage-your-book.firebasestorage.app',
    measurementId: 'G-5M77NLYWXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI0rA7jCgnfkNsoqCymI3-hOfbgBExFww',
    appId: '1:647964169962:android:de2bd8a2ef53cb22e1e993',
    messagingSenderId: '647964169962',
    projectId: 'manage-your-book',
    storageBucket: 'manage-your-book.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSM72kpuTNfmytuQ9ahCA5vmNW47Mhan0',
    appId: '1:647964169962:ios:6df3cc7da6edc9e8e1e993',
    messagingSenderId: '647964169962',
    projectId: 'manage-your-book',
    storageBucket: 'manage-your-book.firebasestorage.app',
    iosBundleId: 'com.example.tekberFp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSM72kpuTNfmytuQ9ahCA5vmNW47Mhan0',
    appId: '1:647964169962:ios:6df3cc7da6edc9e8e1e993',
    messagingSenderId: '647964169962',
    projectId: 'manage-your-book',
    storageBucket: 'manage-your-book.firebasestorage.app',
    iosBundleId: 'com.example.tekberFp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_63AgXRjW-VW7rp7ACEy_GphjthMIHdY',
    appId: '1:647964169962:web:8040d0b94cae3daee1e993',
    messagingSenderId: '647964169962',
    projectId: 'manage-your-book',
    authDomain: 'manage-your-book.firebaseapp.com',
    storageBucket: 'manage-your-book.firebasestorage.app',
    measurementId: 'G-BKPNQVGFRG',
  );
}
